name: Trigger Integration Tests

on: push

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v3
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        otp-version: '26.2.1' # Define the OTP version [required]
        elixir-version: '1.16.3-otp-26' # Define the elixir version [required]
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install dependencies
      run: mix deps.get
    - name: Install testbed dependencies
      run: mix deps.get
      working-directory: ./test_bed
    - name: Run elixir tests
      run: mix test
      working-directory: ./test_bed
