name: Trigger Integration Tests

on: push

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install dependencies
      run: mix deps.get
    - name: Install testbed dependencies
      run: mix deps.get
      working-directory: ./test_bed
    - name: Run elixir tests
      run: mix test
      working-directory: ./test_bed
